name: Python 3.11
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      COVERAGE_THRESHOlD: 80
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow==2.15.*
          pip install torch==2.4.* onnx onnxruntime onnxruntime-extensions
      - name: Run unittests
        run: python -m unittest discover -s tests -v
