name: Run Forward Compatibility Test - Pytorch 2.3 MCTQ v1.5.2
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  run-comp-torch-2_3-v1_5_2:
    uses: ./.github/workflows/forward_compatibility_torch_tests.yml
    with:
      load_version: "v1.5.2"
      python_version: "3.12"
      torch_version: "2.3.*"
